/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Mako.gltf -k -s 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props: any) {
  const { activeHover, ...all } = props;
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Mako.gltf") as any;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const activeAction = activeHover ? "Wave" : "Idle";

    actions?.[activeAction]?.reset().fadeIn(0.2).play();

    return () => {
      actions?.[activeAction]?.fadeOut(0.2);
    };
    // eslint-disable-next-line
  }, [activeHover]);

  return (
    <group ref={group} {...all} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh
            name="Mako"
            geometry={nodes.Mako.geometry}
            material={materials.Atlas}
            skeleton={nodes.Mako.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Mako.gltf");
